name: deep-learning-environment
channels:
  - conda-forge
  - defaults

dependencies:
  # Core
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - notebook
  - nltk
  - gensim

  # Deep Learning
  - pip:
      - tensorflow[and-cuda]   # kalau GPU NVIDIA
      # - tensorflow            # kalau CPU only
      - keras
      - opencv-python
      - scikit-image
      - tqdm
      - joblib
      - h5py
      - Sastrawi
